name: Florida

on:
  schedule:
    - cron: "0 9/12 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "ci"]
    paths:
      - ".github/workflows/build.yml"
      - "patches/**"

jobs: 
  check_version:
    runs-on: ubuntu-22.04

    outputs:
      FRIDA_VERSION: 'v14.2.7'  # 直接指定版本
      ALREADY_RELEASE: ${{ steps.checkReleaseVersion.outputs.ALREADY_RELEASE }}
    steps:
      - name: Split Repository Name
        id: split_name
        run: |
          repo_name=${{ github.repository }}
          IFS='/' read -ra repo_parts <<< "$repo_name"
          echo "owner=${repo_parts[0]}" >> $GITHUB_OUTPUT
          echo "repo=${repo_parts[1]}" >> $GITHUB_OUTPUT

      - name: Check release version
        id: checkReleaseVersion
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const releaseVersion = 'v14.2.7'  // 使用指定版本
              const releaseResponse = await github.repos.getReleaseByTag({
                owner: '${{ steps.split_name.outputs.owner }}',
                repo: '${{ steps.split_name.outputs.repo }}',
                tag: releaseVersion
              });
              const {
                data: { tag_name: ver }
              } = releaseResponse;
              if (ver == 'v14.2.7') {
                  // 根据触发事件设置 ALREADY_RELEASE
                  if ( ${{ ( github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}){
                    core.setOutput('ALREADY_RELEASE', '2');
                  } else {
                    core.setOutput('ALREADY_RELEASE', '1');
                  }
              } else {
                  core.setOutput('ALREADY_RELEASE', '0');
              }
            } catch (e) {
              if(e.message == 'Not Found'){
                core.setOutput('ALREADY_RELEASE', '0');
              } else {
                core.setFailed(e.message);
              }
            }

      - name: Delete release
        if: ${{ steps.checkReleaseVersion.outputs.ALREADY_RELEASE == '2' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: 'v14.2.7'  # 使用指定版本
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

  create_release:
    needs: check_version
    runs-on: ubuntu-22.04
    if: needs.check_version.outputs.ALREADY_RELEASE != '1'

    steps:
      - uses: softprops/action-gh-release@v2.1.0
        id: createRelease
        name: Create Runner Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v14.2.7'  # 使用指定版本
          name: 'v14.2.7'      # 使用指定版本
          prerelease: false

  android_build:
    runs-on: ubuntu-22.04
    needs: [check_version, create_release]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          local-cache: false
          link-to-sdk: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install build-essential tree ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison ruby ruby-dev python3-requests python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386 -y
          sudo gem install fpm -v 1.11.0 --no-document
          python3 -m pip install lief graphlib

      - name: Build Frida for Android
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          
          git clone --recurse-submodules https://github.com/frida/frida
          cd frida
          git checkout v14.2.7  # 切换到指定版本
          
          for path in ../patches/*
          do
            name=$(basename $path)
            real=$(realpath $path)
            echo "Apply patches in $real to frida/subprojects/$name"
            cd subprojects/$name
            git am ../../../patches/$name/*.patch
            cd ../..
          done
          
          ARCHES="android-arm android-arm64 android-x86 android-x86_64"
          for ARCH in $ARCHES
          do
            mkdir build-$ARCH
            cd build-$ARCH
            ../frida/configure --host=$ARCH
            make
            cd ..
          done
      
      - name: Split Repository Name
        id: split_name
        run: |
          repo_name=${{ github.repository }}
          IFS='/' read -ra repo_parts <<< "$repo_name"
          echo "owner=${repo_parts[0]}" >> $GITHUB_OUTPUT
          echo "repo=${repo_parts[1]}" >> $GITHUB_OUTPUT

      - name: Check release version
        id: checkReleaseVersion
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const releaseVersion = 'v14.2.7'  // 使用指定版本
              const releaseResponse = await github.repos.getReleaseByTag({
                owner: '${{ steps.split_name.outputs.owner }}',
                repo: '${{ steps.split_name.outputs.repo }}',
                tag: releaseVersion
              })
              const {
                data: { id: releaseId, html_url: htmlUrl, upload_url: uploadUrl }
              } = releaseResponse;
              core.setOutput('id', releaseId);
              core.setOutput('html_url', htmlUrl);
              core.setOutput('upload_url', uploadUrl);
              core.setOutput('version', releaseVersion);
            } catch (e) {
              core.setFailed(e.message);
            }

      - name: Package build result for Android
        shell: bash
        run: |
          gzip build-android-arm/subprojects/frida-core/server/frida-server
          gzip build-android-arm64/subprojects/frida-core/server/frida-server
          gzip build-android-x86/subprojects/frida-core/server/frida-server
          gzip build-android-x86_64/subprojects/frida-core/server/frida-server
          
          gzip build-android-arm/subprojects/frida-core/inject/frida-inject
          gzip build-android-arm64/subprojects/frida-core/inject/frida-inject
          gzip build-android-x86/subprojects/frida-core/inject/frida-inject
          gzip build-android-x86_64/subprojects/frida-core/inject/frida-inject
          
          gzip build-android-arm/subprojects/frida-core/lib/gadget/frida-gadget.so
          gzip build-android-arm64/subprojects/frida-core/lib/gadget/frida-gadget.so
          gzip build-android-x86/subprojects/frida-core/lib/gadget/frida-gadget.so
          gzip build-android-x86_64/subprojects/frida-core/lib/gadget/frida-gadget.so

          gzip build-android-arm/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a
          gzip build-android-arm64/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a
          gzip build-android-x86/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a
          gzip build-android-x86_64/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a

      - name: Upload android arm frida-server for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm/subprojects/frida-core/server/frida-server.gz'
          asset_name: 'florida-server-v14.2.7-android-arm.gz'
          asset_content_type: application/octet-stream

      - name: Upload android arm64 frida-server for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm64/subprojects/frida-core/server/frida-server.gz'
          asset_name: 'florida-server-v14.2.7-android-arm64.gz'
          asset_content_type: application/octet-stream

      - name: Upload android x86 frida-server for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86/subprojects/frida-core/server/frida-server.gz'
          asset_name: 'florida-server-v14.2.7-android-x86.gz'
          asset_content_type: application/octet-stream

      - name: Upload android x86_64 frida-server for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86_64/subprojects/frida-core/server/frida-server.gz'
          asset_name: 'florida-server-v14.2.7-android-x86_64.gz'
          asset_content_type: application/octet-stream
          
      - name: Upload android arm frida-inject for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm/subprojects/frida-core/inject/frida-inject.gz'
          asset_name: 'florida-inject-v14.2.7-android-arm.gz'
          asset_content_type: application/octet-stream
          
      - name: Upload android arm64 frida-inject for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm64/subprojects/frida-core/inject/frida-inject.gz'
          asset_name: 'florida-inject-v14.2.7-android-arm64.gz'
          asset_content_type: application/octet-stream
          
      - name: Upload android x86 frida-inject for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86/subprojects/frida-core/inject/frida-inject.gz'
          asset_name: 'florida-inject-v14.2.7-android-x86.gz'
          asset_content_type: application/octet-stream
          
      - name: Upload android x86_64 frida-inject for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86_64/subprojects/frida-core/inject/frida-inject.gz'
          asset_name: 'florida-inject-v14.2.7-android-x86_64.gz'
          asset_content_type: application/octet-stream
          
      - name: Upload android arm frida-gadget for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm/subprojects/frida-core/lib/gadget/frida-gadget.so.gz'
          asset_name: 'florida-gadget-v14.2.7-android-arm.so.gz'
          asset_content_type: application/octet-stream

      - name: Upload android arm64 frida-gadget for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm64/subprojects/frida-core/lib/gadget/frida-gadget.so.gz'
          asset_name: 'florida-gadget-v14.2.7-android-arm64.so.gz'
          asset_content_type: application/octet-stream
   
      - name: Upload android x86 frida-gadget for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86/subprojects/frida-core/lib/gadget/frida-gadget.so.gz'
          asset_name: 'florida-gadget-v14.2.7-android-x86.so.gz'
          asset_content_type: application/octet-stream

      - name: Upload android x86_64 frida-gadget for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86_64/subprojects/frida-core/lib/gadget/frida-gadget.so.gz'
          asset_name: 'florida-gadget-v14.2.7-android-x86_64.so.gz'
          asset_content_type: application/octet-stream
     
      - name: Upload android arm frida-gumjs for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a.gz'
          asset_name: 'florida-gumjs-v14.2.7-android-arm.a.gz'
          asset_content_type: application/octet-stream

      - name: Upload android arm64 frida-gumjs for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-arm64/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a.gz'
          asset_name: 'florida-gumjs-v14.2.7-android-arm64.a.gz'
          asset_content_type: application/octet-stream
   
      - name: Upload android x86 frida-gumjs for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a.gz'
          asset_name: 'florida-gumjs-v14.2.7-android-x86.a.gz'
          asset_content_type: application/octet-stream

      - name: Upload android x86_64 frida-gumjs for Florida
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
          asset_path: '${{ github.workspace }}/build-android-x86_64/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a.gz'
          asset_name: 'florida-gumjs-v14.2.7-android-x86_64.a.gz'
          asset_content_type: application/octet-stream
